confirm-before-quit = false

theme = "flow"

copy-on-select = true

[cursor]
shape = 'block'
blinking = true

[bell]
visual = false
audio = false

[editor]
program = "helix"

[fonts]
size = 20
use-drawable-chars = true

[fonts.regular]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "default"

[fonts.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "default"

[fonts.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "default"

[fonts.bold-italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "default"

[window]
mode = "Windowed"
decorations = "Disabled"

[renderer]
performance = "High"
backend = "Vulkan"
target-fps = 120
