-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
-- vim.opt.guicursor = table.concat({
--   "n:block-blinkon0",    -- Normal mode: solid block, no blinking
--   "v:block-blinkwait700-blinkon400-blinkoff250", -- Visual: blinking block
--   "i:block-blinkwait300-blinkon250-blinkoff200", -- Insert: faster blinking
--   "c:ver25",             -- Command-line mode: vertical bar (optional)
--   "r-cr:hor20",          -- Replace modes: horizontal bar
--   "o:hor20",             -- Operator pending mode
-- }, ",")
