#!/bin/bash

options=(
	style=round
	width=6.0
	hidpi=on
	active_color=0xc0e2e2e3
	inactive_color=0xc02c2e34
	background_color=0x302c2e34
)

borders "${options[@]}"

##!/bin/bash
#
#options=(
#	style=round
#  hidpi=on
#	width=5.0
#	active_color=0xffe2e2e3
#	inactive_color=0xff414550
#)
#
#borders "${options[@]}"
