fork = false
frame = "none"
idle = true
maximized = true
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
title-hidden = true
vsync = true
wsl = false

[font]
normal = ["JetBrainsMono Nerd Font"]
bold = ["JetBrainsMono Nerd Font"]
italic = ["JetBrainsMono Nerd Font"]
bold_italic = ["JetBrainsMono Nerd Font"]
size = 13.0
hinting = "full"
edging = "antialias"
